/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author admin
 */
public class ExcellencyGradeGUI extends javax.swing.JPanel implements ActionListener {
    private ReservationGUI r;
    private String seatNo;
    /**
     * Creates new form ExcellencyGradeGUI
     */
    public ExcellencyGradeGUI() {
        initComponents();
    }
    
    public ExcellencyGradeGUI(ReservationGUI r) {
        this();
        this.r=r;
        setVisible(true);
        getEvent();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        btSeatConfirm = new javax.swing.JButton();
        lbBusNo = new javax.swing.JLabel();
        btA05 = new javax.swing.JButton();
        btA01 = new javax.swing.JButton();
        btA02 = new javax.swing.JButton();
        btA03 = new javax.swing.JButton();
        btA04 = new javax.swing.JButton();
        btA15 = new javax.swing.JButton();
        btA18 = new javax.swing.JButton();
        btA17 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btA16 = new javax.swing.JButton();
        btA10 = new javax.swing.JButton();
        btA06 = new javax.swing.JButton();
        btA09 = new javax.swing.JButton();
        btA27 = new javax.swing.JButton();
        btA07 = new javax.swing.JButton();
        btA28 = new javax.swing.JButton();
        btA13 = new javax.swing.JButton();
        btA12 = new javax.swing.JButton();
        btA08 = new javax.swing.JButton();
        btA11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btA26 = new javax.swing.JButton();
        btA25 = new javax.swing.JButton();
        btA24 = new javax.swing.JButton();
        btA23 = new javax.swing.JButton();
        btA22 = new javax.swing.JButton();
        btA21 = new javax.swing.JButton();
        btA20 = new javax.swing.JButton();
        btA19 = new javax.swing.JButton();
        lbSeatInfo = new javax.swing.JLabel();

        jButton35.setBackground(new java.awt.Color(0, 204, 0));
        jButton35.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        jButton36.setBackground(new java.awt.Color(0, 204, 0));
        jButton36.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        jButton37.setBackground(new java.awt.Color(0, 204, 0));
        jButton37.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        jButton38.setBackground(new java.awt.Color(0, 204, 0));
        jButton38.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btSeatConfirm.setText("좌석선택");
        btSeatConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeatConfirmActionPerformed(evt);
            }
        });

        lbBusNo.setText("우등 (28인승) 좌석표");

        btA05.setBackground(new java.awt.Color(0, 204, 0));
        btA05.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA01.setBackground(new java.awt.Color(0, 204, 0));
        btA01.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA02.setBackground(new java.awt.Color(0, 204, 0));
        btA02.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA03.setBackground(new java.awt.Color(0, 204, 0));
        btA03.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA04.setBackground(new java.awt.Color(0, 204, 0));
        btA04.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA15.setBackground(new java.awt.Color(0, 204, 0));
        btA15.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA18.setBackground(new java.awt.Color(0, 204, 0));
        btA18.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA17.setBackground(new java.awt.Color(0, 204, 0));
        btA17.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        jButton10.setBackground(new java.awt.Color(0, 204, 0));
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA16.setBackground(new java.awt.Color(0, 204, 0));
        btA16.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA10.setBackground(new java.awt.Color(0, 204, 0));
        btA10.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA06.setBackground(new java.awt.Color(0, 204, 0));
        btA06.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA09.setBackground(new java.awt.Color(0, 204, 0));
        btA09.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA27.setBackground(new java.awt.Color(0, 204, 0));
        btA27.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA07.setBackground(new java.awt.Color(0, 204, 0));
        btA07.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA28.setBackground(new java.awt.Color(0, 204, 0));
        btA28.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA13.setBackground(new java.awt.Color(0, 204, 0));
        btA13.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA12.setBackground(new java.awt.Color(0, 204, 0));
        btA12.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA08.setBackground(new java.awt.Color(0, 204, 0));
        btA08.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA11.setBackground(new java.awt.Color(0, 204, 0));
        btA11.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        jLabel1.setText("통로");

        jButton30.setText("운전석");

        jLabel2.setText("출입문");

        btA26.setBackground(new java.awt.Color(0, 204, 0));
        btA26.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA25.setBackground(new java.awt.Color(0, 204, 0));
        btA25.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA24.setBackground(new java.awt.Color(0, 204, 0));
        btA24.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA23.setBackground(new java.awt.Color(0, 204, 0));
        btA23.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA22.setBackground(new java.awt.Color(0, 204, 0));
        btA22.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA21.setBackground(new java.awt.Color(0, 204, 0));
        btA21.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA20.setBackground(new java.awt.Color(0, 204, 0));
        btA20.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btA19.setBackground(new java.awt.Color(0, 204, 0));
        btA19.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btA01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA03, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA04, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA06, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA07, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA08, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btA18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(btA16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btA11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btA24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btA25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btA26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btA23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btA20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btA21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btA22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btA19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton30)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btA09, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btA10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbSeatInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btSeatConfirm)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(btA28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btA27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btA05, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btA15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBusNo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btA22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btA19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btA20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btA21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btA26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btA23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btA24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btA25))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btA11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btA01)
                                    .addComponent(btA18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btA02)
                                    .addComponent(btA17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btA03)
                                    .addComponent(jButton10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btA04)
                                    .addComponent(btA16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btA05)
                                    .addComponent(btA15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btA06)
                                    .addComponent(btA13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btA07)
                                    .addComponent(btA12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btA08)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btA28)
                            .addComponent(btA27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSeatConfirm)
                            .addComponent(lbSeatInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btA09)
                            .addComponent(btA10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSeatConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeatConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSeatConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA01;
    private javax.swing.JButton btA02;
    private javax.swing.JButton btA03;
    private javax.swing.JButton btA04;
    private javax.swing.JButton btA05;
    private javax.swing.JButton btA06;
    private javax.swing.JButton btA07;
    private javax.swing.JButton btA08;
    private javax.swing.JButton btA09;
    private javax.swing.JButton btA10;
    private javax.swing.JButton btA11;
    private javax.swing.JButton btA12;
    private javax.swing.JButton btA13;
    private javax.swing.JButton btA15;
    private javax.swing.JButton btA16;
    private javax.swing.JButton btA17;
    private javax.swing.JButton btA18;
    private javax.swing.JButton btA19;
    private javax.swing.JButton btA20;
    private javax.swing.JButton btA21;
    private javax.swing.JButton btA22;
    private javax.swing.JButton btA23;
    private javax.swing.JButton btA24;
    private javax.swing.JButton btA25;
    private javax.swing.JButton btA26;
    private javax.swing.JButton btA27;
    private javax.swing.JButton btA28;
    private javax.swing.JButton btSeatConfirm;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbBusNo;
    private javax.swing.JLabel lbSeatInfo;
    // End of variables declaration//GEN-END:variables

    private void getEvent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==btSeatConfirm){
            r.setSeatNo(seatNo);
            
        }
    }
}
