/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.view;

import com.member.model.MemberDAO;
import com.member.model.MemberDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class JoinGUI extends javax.swing.JFrame implements ActionListener
{
    private MemberDAO dao;
    private boolean isDuplicated;
    private LoginGUI l;
    private MainGUI m;
    private int mode;
    private String edit_id;
//아이디 중복확인
    public static final int USABLE_ID=1; //아이디 사용가능
    public static final int UNUSABLE_ID=2; //아이디 사용불가
    
    public static final int MEMBER_REGISTER=1;  //회원가입
    public static final int MEMBER_EDIT=2;  //회원정보수정
    
    
    /**
     * Creates new form JoinGUI
     */
    public JoinGUI() {
        initComponents();
        this.setTitle("회원가입");
    }
    
    public JoinGUI(LoginGUI l){
        this();
        this.l=l;
        mode=MEMBER_REGISTER;
        init();
        addEvent();
    }
    
    public JoinGUI(MainGUI m,String id){
        
        this();
        this.m=m;
        edit_id=id;
        mode=MEMBER_EDIT;
        init();
        addEvent();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserId = new javax.swing.JLabel();
        lbUserPwd = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbPn = new javax.swing.JLabel();
        lbPoint1 = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CbEmail = new javax.swing.JComboBox<>();
        tfPn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CbPn = new javax.swing.JComboBox<>();
        tfPn2 = new javax.swing.JTextField();
        lbPoint2 = new javax.swing.JLabel();
        btJoin = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        btDuplicated = new javax.swing.JButton();
        tfUserPwd = new javax.swing.JPasswordField();
        tfEmail2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbUserId.setText("아이디");

        lbUserPwd.setText("비밀번호");

        lbName.setText("이름");

        lbAge.setText("나이");

        lbAddress.setText("주소");

        lbEmail.setText("이메일");

        lbPn.setText("전화번호");

        lbPoint1.setText("포인트");

        jLabel9.setText("@");

        CbEmail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "naver.com", "hanmail.net", "nexon.com", "daum.net", "직접입력" }));

        jLabel10.setText("-");

        jLabel11.setText("-");

        CbPn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "010", "011", "012", "018", "019" }));

        lbPoint2.setText("0");

        btJoin.setText("회원가입");

        btClose.setText("닫기");

        btDuplicated.setText("중복확인");
        btDuplicated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDuplicatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CbPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPn2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addGap(18, 18, 18)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPoint1)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btJoin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btClose))
                                    .addComponent(lbPoint2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUserPwd)
                                    .addComponent(lbName)
                                    .addComponent(lbAge)
                                    .addComponent(lbAddress))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfAddress)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 163, Short.MAX_VALUE)))
                                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(tfUserPwd)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUserId)
                        .addGap(18, 18, 18)
                        .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDuplicated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(tfEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserId)
                    .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDuplicated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserPwd)
                    .addComponent(tfUserPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAge)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddress)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(tfEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPn)
                        .addComponent(jLabel11)
                        .addComponent(CbPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPoint1)
                    .addComponent(lbPoint2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btJoin)
                    .addComponent(btClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDuplicatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDuplicatedActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btDuplicatedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoinGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbEmail;
    private javax.swing.JComboBox<String> CbPn;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDuplicated;
    private javax.swing.JButton btJoin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPn;
    private javax.swing.JLabel lbPoint1;
    private javax.swing.JLabel lbPoint2;
    private javax.swing.JLabel lbUserId;
    private javax.swing.JLabel lbUserPwd;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmail2;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPn;
    private javax.swing.JTextField tfPn2;
    private javax.swing.JTextField tfUserId;
    private javax.swing.JPasswordField tfUserPwd;
    // End of variables declaration//GEN-END:variables

    private void init() {
       dao = new MemberDAO();
       this.setVisible(true);
       setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       tfEmail2.setEnabled(false);
       if(mode==MEMBER_EDIT){
           try {
               load();
           } catch (SQLException ex) {
               Logger.getLogger(JoinGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }

    private void addEvent() {
        btJoin.addActionListener(this);
        btDuplicated.addActionListener(this);
        btClose.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==btJoin && mode==MEMBER_EDIT){
            try {
                MemberDTO dto = new MemberDTO();
                String id=tfUserId.getText();
                dto.setId(id);
                String pwd = tfUserPwd.getText();
                if(pwd==null || pwd.isEmpty()){
                    JOptionPane.showMessageDialog(this, "비밀번호를 입력하세요");
                    tfUserPwd.requestFocus();
                    return;
                }
                dto.setPwd(pwd);
                String name=tfName.getText();
                if(name ==null || name.isEmpty()){
                    JOptionPane.showMessageDialog(this, "이름을 입력하세요");
                    tfName.requestFocus();
                    return;
                }
                dto.setName(name);
                dto.setAge(Integer.parseInt(tfAge.getText()));
                dto.setAddress(tfAddress.getText());
                String email="",pn="";
                dto.setEmail(email);
                dto.setPn(pn);
               
                int cnt = dao.updateMember(dto);
                if(cnt>0){
                    JOptionPane.showMessageDialog(this,"회원정보가 수정되었습니다");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "회원정보 수정에 실패하였습니다");
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(JoinGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(ae.getSource()==btJoin && mode==MEMBER_REGISTER){
            try {
                MemberDTO dto = new MemberDTO();
                String id=tfUserId.getText();
                if(id==null || id.isEmpty()){
                    JOptionPane.showMessageDialog(this, "아이디를 입력하세요");
                    tfUserId.requestFocus();
                    return;
                }
                if(!isDuplicated){
                    JOptionPane.showMessageDialog(this, "아이디 중복확인을 하세요");
                    btDuplicated.requestFocus();
                    return;
                }
                dto.setId(id);
                String pwd = tfUserPwd.getText();
                if(pwd==null || pwd.isEmpty()){
                    JOptionPane.showMessageDialog(this, "비밀번호를 입력하세요");
                    tfUserPwd.requestFocus();
                    return;
                }
                dto.setPwd(pwd);
                String name=tfName.getText();
                if(name ==null || name.isEmpty()){
                    JOptionPane.showMessageDialog(this, "이름을 입력하세요");
                    tfName.requestFocus();
                    return;
                }
                dto.setName(name);
                String age=tfAge.getText();
                if(age!=null && !age.isEmpty())
                    dto.setAge(Integer.parseInt(age));
                dto.setAddress(tfAddress.getText());
                String email="",pn="";
                dto.setEmail(email);
                dto.setPn(pn);
               
                int cnt = dao.insertMember(dto);
                if(cnt>0){
                    JOptionPane.showMessageDialog(this,"회원가입이 완료되었습니다");
                    l.tfUserId.setText(id);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "회원가입에 실패하였습니다");
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(JoinGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else if(ae.getSource()==btDuplicated){
            try {
                int cnt = dao.isDuplicated(tfUserId.getText());
                if(cnt==USABLE_ID){
                    JOptionPane.showMessageDialog(this, "사용가능한 아이디입니다");
                    isDuplicated=true;
                }else{
                    JOptionPane.showMessageDialog(this, "이미 사용중인 아이디입니다");
                }
            } catch (SQLException ex) {
                Logger.getLogger(JoinGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(ae.getSource()==btClose){
            this.dispose();
        }
    }

    private void load() throws SQLException {
        MemberDTO dto = dao.selectByID(edit_id);
        btDuplicated.setEnabled(false);
        tfUserId.setText(dto.getId());
        tfUserId.setEnabled(false);
        tfName.setText(dto.getName());
        tfAge.setText(Integer.toString(dto.getAge()));
        tfAddress.setText(dto.getAddress());
        lbPoint2.setText(Integer.toString(dto.getPoint()));
        btJoin.setText("회원정보 수정");
        this.setTitle("회원정보 수정");
    }
}
