/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.view;

import com.member.model.MemberDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class LoginGUI extends javax.swing.JFrame implements ActionListener{
    public static final int LOGIN_OK=1;  //로그인 성공
    public static final int PWD_DISAGREE=2; //비밀번호 불일치
    public static final int USERID_NONE=3;  //해당 아이디 존재하지 않음
    
    private MemberDAO dao;
    /**
     * Creates new form JoinGUI
     */
    public LoginGUI() {
        initComponents();
        init();
        getEvent();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserId = new javax.swing.JLabel();
        lbUserPwd = new javax.swing.JLabel();
        tfUserId = new javax.swing.JTextField();
        tfUserPwd = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        btJoin = new javax.swing.JButton();
        btManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbUserId.setText("아이디");

        lbUserPwd.setText("비밀번호");

        btLogin.setText("로그인");

        btJoin.setText("회원가입");

        btManager.setText("관리자모드");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUserPwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUserPwd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUserId)
                        .addGap(24, 24, 24)
                        .addComponent(tfUserId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btJoin)
                        .addGap(18, 18, 18)
                        .addComponent(btManager)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserId)
                    .addComponent(tfUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUserPwd)
                    .addComponent(tfUserPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btLogin)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btJoin)
                    .addComponent(btManager))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJoin;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btManager;
    private javax.swing.JLabel lbUserId;
    private javax.swing.JLabel lbUserPwd;
    public javax.swing.JTextField tfUserId;
    private javax.swing.JTextField tfUserPwd;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
       if(ae.getSource()==btJoin){
           JoinGUI j =new JoinGUI(this);
       }else if(ae.getSource()==btLogin){
           try {
               String id=tfUserId.getText();
               String pwd=tfUserPwd.getText();
               if(dao.loginCheck(id, pwd)==LOGIN_OK){
                   JOptionPane.showMessageDialog(this, "로그인에 성공하였습니다");
                   this.dispose();
                   MainGUI m = new MainGUI(id);
               }
               else if(dao.loginCheck(id, pwd)==PWD_DISAGREE){
                   JOptionPane.showMessageDialog(this, "비밀번호가 일치하지 않습니다");
                   tfUserPwd.requestFocus();
               }else{
                   JOptionPane.showMessageDialog(this, "해당 아이디가 존재하지 않습니다");
                   tfUserId.requestFocus();
               }
           } catch (SQLException ex) {
               Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }

    private void getEvent() {
        btJoin.addActionListener(this);
        btLogin.addActionListener(this);
    }

    private void init() {
        setTitle("로그인");
        dao=new MemberDAO();
    }
}
