/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author admin
 */
public class NormalGradeGUI extends javax.swing.JFrame implements ActionListener{
    private ReservationGUI r;
    private String seatNo;
    /**
     * Creates new form NormalGradePanel
     */
    public NormalGradeGUI() {
        initComponents();
    }
    public NormalGradeGUI(ReservationGUI r) {
        this(); 
        this.r=r;
        setVisible(true);
        getEvent();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBusNo = new javax.swing.JLabel();
        btN05 = new javax.swing.JButton();
        btN01 = new javax.swing.JButton();
        btN02 = new javax.swing.JButton();
        btN03 = new javax.swing.JButton();
        btN04 = new javax.swing.JButton();
        btN18 = new javax.swing.JButton();
        btN22 = new javax.swing.JButton();
        btN21 = new javax.swing.JButton();
        btN20 = new javax.swing.JButton();
        btN19 = new javax.swing.JButton();
        btN14 = new javax.swing.JButton();
        btN06 = new javax.swing.JButton();
        btN09 = new javax.swing.JButton();
        btN31 = new javax.swing.JButton();
        btN07 = new javax.swing.JButton();
        btN37 = new javax.swing.JButton();
        btN17 = new javax.swing.JButton();
        btN16 = new javax.swing.JButton();
        btN08 = new javax.swing.JButton();
        btN15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btN38 = new javax.swing.JButton();
        btN39 = new javax.swing.JButton();
        btN40 = new javax.swing.JButton();
        btN41 = new javax.swing.JButton();
        btN42 = new javax.swing.JButton();
        btN25 = new javax.swing.JButton();
        btN24 = new javax.swing.JButton();
        btN23 = new javax.swing.JButton();
        lbSeatInfo = new javax.swing.JLabel();
        btN26 = new javax.swing.JButton();
        btN27 = new javax.swing.JButton();
        btN28 = new javax.swing.JButton();
        btN45 = new javax.swing.JButton();
        btN44 = new javax.swing.JButton();
        btN43 = new javax.swing.JButton();
        btN29 = new javax.swing.JButton();
        btN30 = new javax.swing.JButton();
        btN11 = new javax.swing.JButton();
        btN13 = new javax.swing.JButton();
        btN32 = new javax.swing.JButton();
        btN36 = new javax.swing.JButton();
        btN10 = new javax.swing.JButton();
        btN33 = new javax.swing.JButton();
        btN12 = new javax.swing.JButton();
        btN34 = new javax.swing.JButton();
        btN35 = new javax.swing.JButton();
        btSeatConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbBusNo.setText("일반 (45인승) 좌석표");

        btN05.setBackground(new java.awt.Color(0, 204, 0));
        btN05.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN01.setBackground(new java.awt.Color(0, 204, 0));
        btN01.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN02.setBackground(new java.awt.Color(0, 204, 0));
        btN02.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN03.setBackground(new java.awt.Color(0, 204, 0));
        btN03.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN04.setBackground(new java.awt.Color(0, 204, 0));
        btN04.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN18.setBackground(new java.awt.Color(0, 204, 0));
        btN18.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN22.setBackground(new java.awt.Color(0, 204, 0));
        btN22.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN21.setBackground(new java.awt.Color(0, 204, 0));
        btN21.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN20.setBackground(new java.awt.Color(0, 204, 0));
        btN20.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN19.setBackground(new java.awt.Color(0, 204, 0));
        btN19.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN14.setBackground(new java.awt.Color(0, 204, 0));
        btN14.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN06.setBackground(new java.awt.Color(0, 204, 0));
        btN06.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN09.setBackground(new java.awt.Color(0, 204, 0));
        btN09.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN31.setBackground(new java.awt.Color(0, 204, 0));
        btN31.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN07.setBackground(new java.awt.Color(0, 204, 0));
        btN07.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN37.setBackground(new java.awt.Color(0, 204, 0));
        btN37.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN17.setBackground(new java.awt.Color(0, 204, 0));
        btN17.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN16.setBackground(new java.awt.Color(0, 204, 0));
        btN16.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN08.setBackground(new java.awt.Color(0, 204, 0));
        btN08.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN15.setBackground(new java.awt.Color(0, 204, 0));
        btN15.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        jLabel1.setText("통로");

        jButton30.setText("운전석");

        jLabel2.setText("출입문");

        btN38.setBackground(new java.awt.Color(0, 204, 0));
        btN38.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN39.setBackground(new java.awt.Color(0, 204, 0));
        btN39.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN40.setBackground(new java.awt.Color(0, 204, 0));
        btN40.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN41.setBackground(new java.awt.Color(0, 204, 0));
        btN41.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN42.setBackground(new java.awt.Color(0, 204, 0));
        btN42.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN25.setBackground(new java.awt.Color(0, 204, 0));
        btN25.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN24.setBackground(new java.awt.Color(0, 204, 0));
        btN24.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN23.setBackground(new java.awt.Color(0, 204, 0));
        btN23.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        lbSeatInfo.setText("             ");

        btN26.setBackground(new java.awt.Color(0, 204, 0));
        btN26.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN27.setBackground(new java.awt.Color(0, 204, 0));
        btN27.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN28.setBackground(new java.awt.Color(0, 204, 0));
        btN28.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN45.setBackground(new java.awt.Color(0, 204, 0));
        btN45.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN44.setBackground(new java.awt.Color(0, 204, 0));
        btN44.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN43.setBackground(new java.awt.Color(0, 204, 0));
        btN43.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN29.setBackground(new java.awt.Color(0, 204, 0));
        btN29.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN30.setBackground(new java.awt.Color(0, 204, 0));
        btN30.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN11.setBackground(new java.awt.Color(0, 204, 0));
        btN11.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN13.setBackground(new java.awt.Color(0, 204, 0));
        btN13.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN32.setBackground(new java.awt.Color(0, 204, 0));
        btN32.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN36.setBackground(new java.awt.Color(0, 204, 0));
        btN36.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN10.setBackground(new java.awt.Color(0, 204, 0));
        btN10.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN33.setBackground(new java.awt.Color(0, 204, 0));
        btN33.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN12.setBackground(new java.awt.Color(0, 204, 0));
        btN12.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN34.setBackground(new java.awt.Color(0, 204, 0));
        btN34.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btN35.setBackground(new java.awt.Color(0, 204, 0));
        btN35.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\BusReservationSystem\\images\\icons\\seat.png")); // NOI18N

        btSeatConfirm.setText("좌석선택");
        btSeatConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeatConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btN01, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN02, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN03, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN04, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN06, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN07, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN08, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btN22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btN20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(btN19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btN15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btN09, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btN14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btN28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btN27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btN26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btN29, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btN30, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btN40, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btN39, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btN38, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btN41, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btN42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btN25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btN24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btN23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btN43, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btN44, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btN45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btN31, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btN37, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btN05, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btN18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btN10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btN13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btN32, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btN36, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btN11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btN12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbSeatInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSeatConfirm)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btN33, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(btN34, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btN35, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton30)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btN35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbBusNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btN01)
                                            .addComponent(btN22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btN02)
                                            .addComponent(btN21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btN03)
                                            .addComponent(btN20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btN04)
                                            .addComponent(btN19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btN05)
                                            .addComponent(btN18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btN06)
                                            .addComponent(btN17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addComponent(btN08))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btN23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btN24)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btN25))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btN45)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btN44)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btN43)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btN42)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btN38))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btN41)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btN40)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btN30))
                                                                    .addComponent(btN29)
                                                                    .addComponent(btN39)))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btN26)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btN27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btN28))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btN07)
                                                    .addComponent(btN16))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btN15)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btN37)
                            .addComponent(btN31)
                            .addComponent(btN09)
                            .addComponent(btN14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btN13)
                            .addComponent(btN10)
                            .addComponent(btN32)
                            .addComponent(btN36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btN12)
                            .addComponent(btN11)
                            .addComponent(btN33)
                            .addComponent(btN34))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSeatConfirm)
                    .addComponent(lbSeatInfo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSeatConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeatConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSeatConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormalGradeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormalGradeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormalGradeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormalGradeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NormalGradeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btN01;
    private javax.swing.JButton btN02;
    private javax.swing.JButton btN03;
    private javax.swing.JButton btN04;
    private javax.swing.JButton btN05;
    private javax.swing.JButton btN06;
    private javax.swing.JButton btN07;
    private javax.swing.JButton btN08;
    private javax.swing.JButton btN09;
    private javax.swing.JButton btN10;
    private javax.swing.JButton btN11;
    private javax.swing.JButton btN12;
    private javax.swing.JButton btN13;
    private javax.swing.JButton btN14;
    private javax.swing.JButton btN15;
    private javax.swing.JButton btN16;
    private javax.swing.JButton btN17;
    private javax.swing.JButton btN18;
    private javax.swing.JButton btN19;
    private javax.swing.JButton btN20;
    private javax.swing.JButton btN21;
    private javax.swing.JButton btN22;
    private javax.swing.JButton btN23;
    private javax.swing.JButton btN24;
    private javax.swing.JButton btN25;
    private javax.swing.JButton btN26;
    private javax.swing.JButton btN27;
    private javax.swing.JButton btN28;
    private javax.swing.JButton btN29;
    private javax.swing.JButton btN30;
    private javax.swing.JButton btN31;
    private javax.swing.JButton btN32;
    private javax.swing.JButton btN33;
    private javax.swing.JButton btN34;
    private javax.swing.JButton btN35;
    private javax.swing.JButton btN36;
    private javax.swing.JButton btN37;
    private javax.swing.JButton btN38;
    private javax.swing.JButton btN39;
    private javax.swing.JButton btN40;
    private javax.swing.JButton btN41;
    private javax.swing.JButton btN42;
    private javax.swing.JButton btN43;
    private javax.swing.JButton btN44;
    private javax.swing.JButton btN45;
    private javax.swing.JButton btSeatConfirm;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBusNo;
    private javax.swing.JLabel lbSeatInfo;
    // End of variables declaration//GEN-END:variables

    private void getEvent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==btSeatConfirm){
            r.setSeatNo(seatNo);
            dispose();
        }
    }
}
