/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.view;

import com.bus.model.BusDAO;
import com.bus.model.BusDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.JComboBox;

/**
 *
 * @author admin
 */
public class ReservationGUI extends javax.swing.JFrame implements ItemListener,ActionListener{
    private BusDAO busDao;
    private int busNo;
    private boolean isCbSelected1;
    private boolean isCbSelected2;
    private boolean isCbSelected3;
    private boolean isCbSelected4;
    private List<String> seatNo;
    private String grade;

    public int busNo(){
        return busNo;
    }
    
    public void setSeatNo(String seatNo) {
        this.seatNo.add(seatNo);
    }
    
    /**
     * Creates new form ReservationGUI
     */
    public ReservationGUI() {
        initComponents();
    }
    public ReservationGUI(int busNo,String grade){
        this();
        busDao=new BusDAO();
        setVisible(true);
        seatNo=new ArrayList<String>();
        this.busNo=busNo;
        this.grade=grade;
        init();
        addEvent();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbStart = new javax.swing.JLabel();
        lbEnd = new javax.swing.JLabel();
        lbStartDate = new javax.swing.JLabel();
        lbStartTime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbGrade = new javax.swing.JLabel();
        cbSelect1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbSelect2 = new javax.swing.JComboBox<>();
        cbSelect3 = new javax.swing.JComboBox<>();
        cbSelect4 = new javax.swing.JComboBox<>();
        btSelect1 = new javax.swing.JButton();
        btSelect2 = new javax.swing.JButton();
        btSelect3 = new javax.swing.JButton();
        btSelect4 = new javax.swing.JButton();
        lbSeat1 = new javax.swing.JLabel();
        lbSeat2 = new javax.swing.JLabel();
        lbSeat3 = new javax.swing.JLabel();
        lbSeat4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("출발지");

        jLabel2.setText("도착지");

        jLabel3.setText("운행날짜");

        jLabel4.setText("출발시각");

        lbStart.setText("                 ");

        lbEnd.setText("                 ");

        lbStartDate.setText("                   ");

        lbStartTime.setText("                      ");

        jLabel9.setText("등급");

        lbGrade.setText("             ");

        cbSelect1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "해당없음", "대인", "소인", " " }));

        jLabel6.setText("* 한번 예매시 최대 4인까지 가능");

        cbSelect2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "해당없음", "대인", "소인", " " }));

        cbSelect3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "해당없음", "대인", "소인", " " }));

        cbSelect4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "해당없음", "대인", "소인", " " }));

        btSelect1.setText("좌석조회");

        btSelect2.setText("좌석조회");
        btSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelect2ActionPerformed(evt);
            }
        });

        btSelect3.setText("좌석조회");

        btSelect4.setText("좌석조회");

        lbSeat1.setText("                  ");

        lbSeat2.setText("                ");

        lbSeat3.setText("             ");

        lbSeat4.setText("              ");

        jButton2.setText("결제");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSelect2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSeat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSelect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSelect4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSeat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSelect3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSelect3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSeat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbGrade)
                            .addComponent(lbStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSelect1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSeat1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbStart))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbEnd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbStartDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbStartTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbGrade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSelect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelect1)
                    .addComponent(lbSeat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSelect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelect2)
                    .addComponent(lbSeat2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSelect3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelect3)
                    .addComponent(lbSeat3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSelect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelect4)
                    .addComponent(lbSeat4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelect2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSelect2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelect1;
    private javax.swing.JButton btSelect2;
    private javax.swing.JButton btSelect3;
    private javax.swing.JButton btSelect4;
    private javax.swing.JComboBox<String> cbSelect1;
    private javax.swing.JComboBox<String> cbSelect2;
    private javax.swing.JComboBox<String> cbSelect3;
    private javax.swing.JComboBox<String> cbSelect4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbGrade;
    private javax.swing.JLabel lbSeat1;
    private javax.swing.JLabel lbSeat2;
    private javax.swing.JLabel lbSeat3;
    private javax.swing.JLabel lbSeat4;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbStartTime;
    // End of variables declaration//GEN-END:variables

    private void init() {
        BusDTO dto=null;
        try {
            dto = busDao.selectByBusNo(busNo);
        } catch (SQLException ex) {
            Logger.getLogger(ReservationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbStart.setText(dto.getStart());
        lbEnd.setText(dto.getEnd());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy 년 MM 월 dd 일");
        String date =sdf.format(dto.getStartDate());
        lbStartDate.setText(date);
        lbStartTime.setText(dto.getStartTime());
        lbGrade.setText(dto.getGrade());
        btSelect1.setEnabled(false);
        btSelect2.setEnabled(false);
        btSelect3.setEnabled(false);
        btSelect4.setEnabled(false);
        
    }

    private void addEvent() {
        cbSelect1.addItemListener(this);
        cbSelect2.addItemListener(this);
        cbSelect3.addItemListener(this);
        cbSelect4.addItemListener(this);
    }

    @Override
    public void itemStateChanged(ItemEvent ie) {
        if(ie.getSource()==cbSelect1 && !((String)(cbSelect1.getSelectedItem())).equals("해당없음")){
            btSelect1.setEnabled(true);
            return;
        }
        else if(ie.getSource()==cbSelect1 && ((String)(cbSelect1.getSelectedItem())).equals("해당없음")){
            btSelect1.setEnabled(false);
            return;
        }
        else if(ie.getSource()==cbSelect2 && !((String)(cbSelect2.getSelectedItem())).equals("해당없음")){
            btSelect2.setEnabled(true);
            return;
        }
        else if(ie.getSource()==cbSelect2 && ((String)(cbSelect2.getSelectedItem())).equals("해당없음")){
            btSelect2.setEnabled(false);
            return;
        }
        else if(ie.getSource()==cbSelect3 && !((String)(cbSelect3.getSelectedItem())).equals("해당없음")){
            btSelect3.setEnabled(true);
            return;
        }
        else if(ie.getSource()==cbSelect3 && ((String)(cbSelect3.getSelectedItem())).equals("해당없음")){
            btSelect3.setEnabled(false);
            return;
        }
        else if(ie.getSource()==cbSelect4 && !((String)(cbSelect4.getSelectedItem())).equals("해당없음")){
            btSelect4.setEnabled(true);
            return;
        }
        else if(ie.getSource()==cbSelect4 && ((String)(cbSelect4.getSelectedItem())).equals("해당없음")){
            btSelect4.setEnabled(false);
            return;
        }
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource()==btSelect1 || ae.getSource()==btSelect2 || ae.getSource()==btSelect3 || ae.getSource()==btSelect4){
            if(grade.equals("일반")){
                NormalGradeGUI n = new NormalGradeGUI(this);
                return;
            }else if(grade.equals("우등")){
                ExcellencyGradeGUI e = new ExcellencyGradeGUI(this);
                return;
            }else{
                PremiumGradeGUI p = new PremiumGradeGUI(this);
                return;
            }
            
        }
    }
    
}
